name: Run on Contabo

on:
  push:
    branches:
      - main
  workflow_dispatch:   # manual trigger from Actions tab

jobs:
  run-on-server:
    runs-on: ubuntu-latest  # GitHub runner just runs SSH, real work is on your server
    steps:
      - name: Run command on Contabo server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}       # your Contabo server IP
          username: ${{ secrets.SERVER_USER }} # your server username
          key: ${{ secrets.SERVER_SSH_KEY }}   # your private SSH key stored in GitHub Secrets
          port: 22
          script: |
            cd ~/show-name-pipeline
            git pull origin main
            echo "Jahid"
